name: Android build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 240

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Export settings from npm package
      run: |
        npm run export_npm_env

    #- name Install coreutils
    #  run: |
    #    brew install coreutils

    - name: Setup V8 build environment & fetch code
      run: |
        scripts/setup.sh -r ${V8_VERSION} android

    - name: Patch V8
      run: |
        scripts/patch.sh android

    - name: Build V8
      run: |
        scripts/build.sh android

    - name: Archive V8
      run: |
        scripts/archive.sh android

    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist