name: iOS build

on: [push]

jobs:
  build:
    runs-on: macOS-10.15
    timeout-minutes: 240

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Export settings from npm package
      run: |
        npm run export_npm_env

    - name Install coreutils
      run: |
        brew install coreutils

    - name: Setup V8 build environment & fetch code
      run: |
        scripts/setup.sh -r ${V8_VERSION} ios

    - name: Patch V8
      run: |
        scripts/patch.sh ios

    - name: Build V8
      run: |
        scripts/build.sh ios

    - name: Archive V8
      run: |
        scripts/archive.sh ios

    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
